name: "flair_align"
description: Aligns long reads to the genome using minimap2 and converts to BED12 format
keywords:
  - long-read
  - alignment
  - isoform
  - transcriptome
  - nanopore
  - pacbio
tools:
  - flair:
      description: Full-Length Alternative Isoform analysis of RNA
      homepage: https://github.com/BrooksLabUCSC/flair
      documentation: https://flair.readthedocs.io/en/latest/
      tool_dev_url: https://github.com/BrooksLabUCSC/flair
      doi: "10.1038/s41467-020-15171-6"
      licence: ["MIT"]
      identifier: biotools:flair

input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1' ]`
    - reads:
        type: file
        description: Input FASTQ or FASTA file of long reads
        pattern: "*.{fastq,fq,fasta,fa,fastq.gz,fq.gz,fasta.gz,fa.gz}"
  - - meta2:
        type: map
        description: |
          Groovy Map containing reference information
          e.g. `[ id:'genome' ]`
    - genome:
        type: file
        description: Reference genome FASTA file
        pattern: "*.{fasta,fa,fasta.gz,fa.gz}"

output:
  - bam:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1' ]`
      - "*.aligned.bam":
          type: file
          description: Aligned BAM file
          pattern: "*.aligned.bam"
  - bai:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1' ]`
      - "*.aligned.bam.bai":
          type: file
          description: BAM index file
          pattern: "*.aligned.bam.bai"
  - bed:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1' ]`
      - "*.aligned.bed":
          type: file
          description: Aligned reads in BED12 format
          pattern: "*.aligned.bed"
  - versions_flair:
      - "${task.process}":
          type: string
          description: Process name
      - flair:
          type: string
          description: Tool name
      - version:
          type: string
          description: Tool version

authors:
  - "@SiYangming"
maintainers:
  - "@SiYangming"
