name: "longshot"
description: Longshot is a variant caller for long read data (Oxford Nanopore, PacBio, etc.)
keywords:
  - variant calling
  - long reads
  - nanopore
  - pacbio
tools:
  - "longshot":
      description: "Longshot: Long-read SNV caller"
      homepage: "https://github.com/pjedge/longshot"
      documentation: "https://github.com/pjedge/longshot"
      tool_dev_url: "https://github.com/pjedge/longshot"
      doi: "10.1038/s41467-019-12493-y"
      licence: ["MIT"]
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'test', single_end:false ]`
    - bam:
        type: file
        description: Input BAM file
        pattern: "*.bam"
    - bai:
        type: file
        description: Input BAM index file
        pattern: "*.bai"
  - - meta2:
        type: map
        description: |
          Groovy Map containing reference information
          e.g. `[ id:'genome' ]`
    - fasta:
        type: file
        description: Reference genome FASTA file
        pattern: "*.{fa,fasta}"
    - fai:
        type: file
        description: Reference genome FASTA index file
        pattern: "*.fai"
  - - region:
        type: string
        description: Optional region string (e.g. "chr20:1000-2000")
output:
  - vcf:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
      - "*.vcf":
          type: file
          description: Output VCF file
          pattern: "*.vcf"
  - versions:
      - versions.yml:
          type: file
          description: File containing software versions
          pattern: "versions.yml"
authors:
  - "@siyangming"
