name: "flair_diffexp"
description: Performs differential expression analysis between two conditions using DESeq2
keywords:
  - long-read
  - differential-expression
  - isoform
  - deseq2
tools:
  - flair:
      description: Full-Length Alternative Isoform analysis of RNA
      homepage: https://github.com/BrooksLabUCSC/flair
      documentation: https://flair.readthedocs.io/en/latest/
      tool_dev_url: https://github.com/BrooksLabUCSC/flair
      doi: "10.1038/s41467-020-15171-6"
      licence: ["MIT"]
      identifier: biotools:flair

input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'experiment1' ]`
    - counts:
        type: file
        description: Counts matrix from FLAIR quantify
        pattern: "*.counts.tsv"
  - - meta2:
        type: map
        description: |
          Groovy Map containing isoform information
          e.g. `[ id:'isoforms' ]`
    - isoforms:
        type: file
        description: Isoforms reference file (BED format from collapse or transcriptome, optional)
        pattern: "*.bed"

output:
  - deseq2_results:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'experiment1' ]`
      - "*_deseq2_results.tsv":
          type: file
          description: DESeq2 differential expression results
          pattern: "*_deseq2_results.tsv"
  - deseq2_plots:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'experiment1' ]`
      - "*_*deseq2*.pdf":
          type: file
          description: DESeq2 diagnostic plots
          pattern: "*_*deseq2*.pdf"
  - versions_flair:
      - "${task.process}":
          type: string
          description: Process name
      - flair:
          type: string
          description: Tool name
      - version:
          type: string
          description: Tool version

authors:
  - "@SiYangming"
maintainers:
  - "@SiYangming"
