# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/subworkflows/yaml-schema.json
name: "minimap2_longshot_flair"
description: "Align reads with Minimap2, call variants with Longshot, and run Flair variants"
keywords:
  - alignment
  - variant_calling
  - isoforms
  - flair
  - longshot
components:
  - minimap2/align
  - longshot
  - flair/variants
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'test', single_end:false ]`
    - reads:
        type: file
        description: Input reads (FASTQ/FASTA)
        pattern: "*.{fastq,fastq.gz,fasta,fasta.gz,fa,fa.gz,fq,fq.gz}"
  - - meta2:
        type: map
        description: |
          Groovy Map containing reference information
          e.g. `[ id:'genome' ]`
    - fasta:
        type: file
        description: Reference genome FASTA file
        pattern: "*.{fa,fasta}"
    - fai:
        type: file
        description: Reference genome FASTA index file
        pattern: "*.fai"
  - - meta3:
        type: map
        description: |
          Groovy Map containing sample information (must match reads)
          e.g. `[ id:'test' ]`
    - bam:
        type: file
        description: BAM file for Flair quantification (optional/if different from alignment)
        pattern: "*.bam"
  - - meta4:
        type: map
        description: |
          Groovy Map containing sample information (must match reads)
          e.g. `[ id:'test' ]`
    - isoforms_fa:
        type: file
        description: Isoforms FASTA file
        pattern: "*.{fa,fasta}"
  - - meta5:
        type: map
        description: |
          Groovy Map containing sample information (must match reads)
          e.g. `[ id:'test' ]`
    - isoforms_bed:
        type: file
        description: Isoforms BED file
        pattern: "*.bed"
  - - gtf:
        type: file
        description: Reference GTF annotation
        pattern: "*.gtf"
output:
  - variants:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'test', single_end:false ]`
      - "*.vcf":
          type: file
          description: Output VCF file
          pattern: "*.vcf"
  - versions:
      - versions.yml:
          type: file
          description: File containing software versions
          pattern: "versions.yml"
authors:
  - "@siyangming"
